namespace androkat.domain.Enum;

public enum Forras
{
    mello = 1,
    pio = 2,
    janospal = 3,
    sztjanos = 4,
    kisterez = 5,
    audiohorvath = 6,
    fokolare = 7,
    terezanya = 8,
    papaitwitter = 9,
    advent = 10,
    maievangelium = 11,
    ignac = 12,
    barsi = 13,
    horvath = 14,
    prayasyougo = 15,
    nagybojt = 16,
    bojte = 17,
    kurir = 18,
    kempis = 19,
    bonumtv = 20,
    maiszent = 21,
    szeretetujsag = 24,
    humor = 25,
    audionapievangelium = 28,
    keresztenyelet = 29,
    gyonas = 34,
    audiobarsi = 38,
    audiopalferi = 39,
    vianney = 42,
    b777 = 43,
    regnum = 45,
    book = 46,
    taize = 47,
    prohaszka = 48,
    bzarandokma = 49,
    szentbernat = 50,
    jezsuitablog = 51,
    szentszalezi = 52,
    laciatya = 57,
    ajanlatweb = 58,
    audiotaize = 60,
    sienaikatalin = 61,
    medjugorje = 62
}