name: build and test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'src/androkat.maui/**'
    - 'readme.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'src/androkat.maui/**'
    - 'readme.md'

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION_FILE: './src/androkat.web/androkat.web.sln'
  ANDROKAT_ENDPOINT_SAVE_CONTENT_DETAILS_API_URL: '/test/savecontentdetails'
  ANDROKAT_ENDPOINT_SAVE_TEMP_CONTENT_API_URL: '/test/savetempontent'
  ANDROKAT_ENDPOINT_UPDATE_RADIO_MUSOR_API_URL: '/test/updateradio'
  ANDROKAT_ENDPOINT_HEALTH_CHECK_API_URL: '/health'
  ANDROKAT_ENDPOINT_GET_CONTENTS_API_URL: '/test/contents'
  ANDROKAT_ENDPOINT_CRON: 'testcron'
  ANDROKAT_CREDENTIAL_CRON_API_KEY: 'test-api-key-12345'
  ANDROKAT_GOOGLE_CLIENT_ID: 'test-client-id.apps.googleusercontent.com'
  ANDROKAT_GOOGLE_CLIENT_SECRET: 'test-client-secret-xyz'
  ANDROKAT_GENERAL_HOST_URL: 'https://localhost:5001'
  ANDROKAT_GENERAL_ADMIN: 'test-admin@domain.com'

jobs:
  build-and-test:
    name: build-and-test-ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.SOLUTION_FILE }} --no-build --configuration Release
